### ISSUE TITLE
[SUBS] Error message is not shown anymore

### ISSUE THREAD

**Issue by elvijsTDL** [superfluid-finance/widget#108]
During merging of #102 the "Something went wrong" error message got messed up and is not showing up anymore

Easiest way to reproduce, try to start a transaction and reject it in your wallet, notice how the Not started turns into an empty string and the dot stays grey , this would be very confusing for new users , as there is no indication of stuff going wrong and the button just stays disabled

![Screenshot 2023-07-25 at 15 17 47](https://github.com/superfluid-finance/widget/assets/77115130/7691a289-907e-41b5-bbf0-41c5cb3a0c4a)

**Comment by tokdaniel** [comment]
This was intentional.
