### ISSUE TITLE
[SUBS] Implement Upfront + Ongoing Payment Method

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/widget#132]

**Comment by kasparkallas** [comment]
@0xYoanna link to the designs, please

**Comment by 0xYoanna** [comment]
Figma: https://www.figma.com/file/S2J3MZKdTzlIQT4MUaAksB/Workshop?type=design&node-id=1678-6351&mode=design&t=5mQhWQs5TdSHuXWH-4

**Comment by 0xYoanna** [comment]
Notion: https://www.notion.so/superfluidhq/Upfront-Ongoing-Subscription-Payment-Option-41e23ff02bfd47cb8513eef0238dcc4c

**Comment by kasparkallas** [comment]
Considering adding a guard clause to check previous transfer events to avoid duplicate transfers for the user.
