### ISSUE TITLE
[SUBS] Track Gnosis safe transactions correctly

### ISSUE THREAD

**Issue by elvijsTDL** [superfluid-finance/widget#147]
#145 - solved connecting hosted widgets to Gnosis safe, but although its possible to create and succesfully send the transaction, the widget loses track of it and a gnosis safe user would be stuck in a state like this 
![Screenshot 2023-08-23 at 15 46 44](https://github.com/superfluid-finance/widget/assets/77115130/dfd349f1-31cc-4732-b908-6ece14b21697)

**Comment by kasparkallas** [comment]
Solved by adding the option to skip transaction waiting, allowing the gnosis safe users to go through all the steps.
