### ISSUE TITLE
[SUBS] Add "ensure" behaviour to upfront fee and stream creation/modification

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/widget#155]
**Context**
Because the widget doesn't store state yet, there is a plausible chance that the end-user could accidentally go through the widget's flow multiple times, hence pay the upfront free and add to the flow rate multiple times. 

There is also a possibility that the end-user sends the upfront fee and then gets disconnected from the widget. Upon restarting and going through the widget again, the widget would request for the upfront fee again. We want to avoid this.

It might also not be expected behavior for the subscription process of the widget to always add additional flow rate to the existing stream. In most cases, the expected behaviour might be to ensure a certain flow rate to qualify for the subscription service.

This type of "ensure" behaviour could also be characterized by "idempotency".

**Solution**
- Check the transfers for the payment option with the upfront fee for the time period to figure out whether an upfront fee payment has been made.
- Add an option to flow rate based payment option to ensure a certain flow rate. Note: it should probably never reduce the flow rate.
- When the preconditions are ensured, take the end-user to the success screen?

**Comment by vmichalik** [comment]
no PR for this @kasparkallas, I don't think this was covered in #184 right? in progress or back to sprint backlog?
