### ISSUE TITLE
Add "Edit" and "Duplicate" buttons to the Checkout Builder's payment options

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/widget#168]
As a developer/merchant,
in the Checkout Builder,
I want to quickly edit and duplicate payment options,
so that I wouldn't waste time inputting the same information many times.

Notes:
- the duplicate button shouldn't instantly duplicate (as that would cause a widget's validation error), instead it should open the "add new payment option" dialog with the existing payment's option filled where it can be tweaked before adding/duplicating
- "duplicate" is maybe not the best word to use
- I'd recommend using MUI's IconButtons with the following icons: "Delete", "Edit", "ContentCopy"

**Comment by tokdaniel** [comment]
Added Edit, and Clone to PaymentOptions
