### ISSUE TITLE
[SUBS] Add ability to capture additional customer data through the checkout widget

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/widget#197]
_As a merchant,
I'd like to capture additional customer data,
when the customer subscribes using the checkout widget._

The customer data is mainly meant as the e-mail address. The widget should treat the data as ephemeral, i.e. it will pass it through using callbacks but will not actually store it anywhere.

To consider:
- should filling the fields be optional or required
  - if it's required then it should be validated before the user can do the transactions
- anything else besides e-mail? (like a phone number)
- should the callback be blocking, i.e. not asynchronous like a listener

**Comment by kasparkallas** [comment]
To get an idea how on Stripe's checkout builder you can enable capturing of "phone number" and other additional data: https://checkout.stripe.dev/configure We want to capture for e-mail.om

**Comment by philipandersson** [comment]
Investigated how to use custom data.
