### ISSUE TITLE
[SUBS] update dependencies (and examples)

### ISSUE THREAD

**Issue by kasparkallas** [superfluid-finance/widget#232]
**Why?**
Falling behind on the dependencies, causing increasing technical debt and uncertainty.

**What?**
* update dependencies for the widget and apps
* update dependencies for examples (most notably web3modal from v2 to v3)
* unify dependencies for docs with rest of monorepo projects

**How?**
`pnpm update --recursive --interactive` (and possibly `--latest`) and fix the issues

**Comment by kasparkallas** [comment]
slight blocker with web3modal as we rely on `isOpen`: https://github.com/orgs/WalletConnect/discussions/4164

**Comment by MidnightLightning** [comment]
This issue indicates it's completed, but I'm not seeing any code changes tagged to this issue, and the tip of `master` has examples that are still out-of-date. Where are the web3modal v3 examples at, @kasparkallas ?
