### ISSUE TITLE
[SUBS] Error States & Input Validation for Widget

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/widget#51]
### Widget Builder
- [x] no payment method selected

### Widget
- Low balance
- Sending to yourself
- crash on unexpected inputs
- ~dig into possible new viem errors~
- ~escape route from error states~
- ~Unfinished sessions & transactions~
- Receiver already has a stream
- Pure super token edge cases

**Comment by kasparkallas** [comment]
Validations before transactions were implemented from this story.

What didn't get implemented is the error handling of the gas estimations and actual transactions.

I'll look into splitting to 2 stories.

**Comment by kasparkallas** [comment]
This is what it looks like when no payment method selected in the Widget Builder:
![image.png](https://images.zenhubusercontent.com/6218aba0c485734ddc9dcb36/cb1c4e90-2d63-4b43-a3c8-fe1764999f04)

Should be good enough for now. Will keep in mind when we re-visit error callbacks from the widget.

**Comment by kasparkallas** [comment]
Example of a validation error from the Widget currently:
![image.png](https://images.zenhubusercontent.com/6218aba0c485734ddc9dcb36/e193f763-84d4-4049-824c-61130cc67781)

Note: will look into making the visual layout look better with @0xYoanna in the future.
